DIR_RAW="/rwproject/kdd-db/hliubs/10_data_spatial/3dor/raw"
# DIR_DB="/rwproject/kdd-db/hliubs/10_data_spatial/3dor/db"
DIR_OBJ_DB="/rwproject/kdd-db/hliubs/10_data_spatial/3dor/db/object_scans"
# DIR_QUERY="/rwproject/kdd-db/hliubs/10_data_spatial/3dor/query"
# DIR_RESULT="/rwproject/kdd-db/hliubs/10_data_spatial/3dor/query_result"
# DIR_INDEX="/rwproject/kdd-db/hliubs/10_data_spatial/3dor/index"
# DIR_STAT="/rwproject/kdd-db/hliubs/10_data_spatial/3dor/stat"

DIR_DB="/ssd/hliubs/3dor_exp/db"
DIR_QUERY="/ssd/hliubs/3dor_exp/query"
DIR_RESULT="/ssd/hliubs/3dor_exp/query_result"
DIR_INDEX="/ssd/hliubs/3dor_exp/index"
DIR_STAT="/ssd/hliubs/3dor_exp/stat"