DIR_RAW="/rwproject/kdd-db/hliubs/10_data_spatial/3dor/raw"
DIR_DB="/rwproject/kdd-db/hliubs/10_data_spatial/3dor/db"
DIR_QUERY="/rwproject/kdd-db/hliubs/10_data_spatial/3dor/query"
DIR_INDEX="/rwproject/kdd-db/hliubs/10_data_spatial/3dor/index"
DIR_STAT="/rwproject/kdd-db/hliubs/10_data_spatial/3dor/stat"